# Generated by Django 4.1.4 on 2023-04-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_emp_age_alter_emp_city_alter_emp_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="city",
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
