# Generated by Django 4.1.4 on 2023-04-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_emp_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="age",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="emp",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
